### PR TITLE
Fixes inconsistencies in pyproject.toml documentation.

### PR DESCRIPTION
**Pull request by thomasbbrunner**
Addresses inconsistencies of the documentation of fields in the pyproject.toml file.

Related to https://github.com/pypa/sampleproject/issues/196.

### CODE REVIEW

**Comment by JonasLoos** [comment]
Specifying `readme = {file = "README.md"}` seems be wrong, according to https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#readme. I also got an error when trying it out locally.

Valid options are:
```
readme = "README.md"  # as previously
```
or
```
readme = {file = "README.md", content-type = "text/markdown"}
```

**Comment by thomasbbrunner** [comment]
True, somehow I missed this. Thanks for taking the time and reporting this.

I'll update the MR, even though there does not seem to be much interest in merging this.

**Review by di — APPROVED** [review]
Thanks!

**Comment by di** [comment]
(Looks like we have some unrelated test failures here that need to be resolved first)

**Pull request merged**
