### PR TITLE
Remove Python 3.5 and add 3.9

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Review by dmtucker — APPROVED** [review]

**Comment by gliptak** [comment]
It is non clear why ```3.6``` Travis failed https://travis-ci.com/github/pypa/sampleproject/jobs/463020338

```
py36 run-test: commands[0] | check-manifest --ignore 'tox.ini,tests/**'
lists of files in version control and sdist do not match!
missing from sdist:
  setup.py
suggested MANIFEST.in rules
  include *.py
ERROR: InvocationError for command /home/travis/build/pypa/sampleproject/.tox/py36/bin/check-manifest --ignore 'tox.ini,tests/**' (exited with code 1)
```

as other runs are green https://travis-ci.com/github/pypa/sampleproject/jobs/463020341

**Comment by di** [comment]
Looks like `check-manifest` is failing on Python 3.6 only with version `0.45` -- it works fine with `0.44`. In addition it appears to only be failing on Travis -- I can't reproduce locally.

@mgedmin Any idea what's going on here? Could this be a regression in `check-manifest`?

**Comment by mgedmin** [comment]
Could be anything, really.  Outdated setuptools/wheel/pip on the Travis VM?  The switch of the PEP-517 build backend (from pep517.build to https://pypi.org/project/build/) could also be relevant.

**Comment by mgedmin** [comment]
(I cannot reproduce locally either, with `pipx run --python python3.6 check-manifest`.)

**Comment by di** [comment]
> Outdated setuptools/wheel/pip on the Travis VM?

Tried updating all of them and still got the same behavior. Is there anything Python 3.6 specific perhaps?

**Comment by mgedmin** [comment]
> Is there anything Python 3.6 specific perhaps?

Nothing comes to mind!

Is check-manifest actually right about the missing `setup.py` in the sdist?  If you would add a `.tox/py36/bin/python -m build --sdist . --outdir /tmp` to the Travis build for 3.6, and then a `tar tvzf /tmp/sampleproject-2.0.0.tar.gz | grep setup.py`, would it find a setup.py?

**Comment by gliptak** [comment]
Considering that `3.6` fail is an existing problem, can this PR move forward?

**Comment by di** [comment]
Looks like the 3.6 failures were a fluke. Thanks @gliptak!

**Pull request merged**
